export { createDb, checkDatabase } from './client.js';
export type { AppDb, TenantTransaction } from './client.js';
export { provisionTenant, ProvisioningConflictError } from './provisioning.js';
export type { ProvisionTenantInput } from './provisioning.js';
export {
  accountCredentials,
  accounts,
  academicClasses,
  academicSections,
  academicSessions,
  academicSubjects,
  academicTeacherAssignments,
  admissionCaseEvents,
  admissionCaseGuardians,
  admissionCases,
  authorizationRolePermissions,
  authorizationRoles,
  appMetadata,
  authRateLimits,
  campuses,
  invitations,
  memberships,
  membershipRoleAssignments,
  permissions,
  passwordResetTokens,
  schools,
  securityEvents,
  sessions,
  staffProfiles,
  staffSchoolAffiliations,
  studentAcademicEnrollments,
  studentGuardianRelationships,
  studentImportBatches,
  studentProfiles,
  studentSchoolEnrollments,
  weeklyTimetableEvents,
  weeklyTimetableSlots,
  weeklyTimetables,
  dailyAttendanceRegisters,
  dailyAttendanceEntries,
  dailyAttendanceEvents,
  feeHeads,
  feePlans,
  feePlanLines,
  feeAssignments,
  feeCharges,
  feeReceiptCounters,
  feePayments,
  feeLedgerEntries,
  guardianProfiles,
  teacherProfiles,
  tenants,
} from './schema.js';
export {
  StaffError,
  normalizeStaffCode,
  normalizeStaffProfile,
  normalizeStaffListFilters,
  createStaffProfile,
  listSchoolStaff,
  listStaffSchools,
  readSchoolStaff,
  listStaffAffiliationSchoolIds,
  updateStaffProfile,
  updateStaffAffiliation,
  addStaffAffiliation,
  upsertTeacherProfile,
  linkStaffMembership,
  unlinkStaffMembership,
  listEligibleStaffAccounts,
  isAssignableTeacher,
  getAttendanceTeacherLink,
  getAttendanceSchool,
  listAttendanceSchools,
  listAssignableTeacherAccounts,
} from './staff.js';
export type { StaffScope, StaffProfileInput, StaffAffiliationInput, StaffCreateInput, StaffListFilters, StaffListPage, StaffRecord, StaffAudit } from './staff.js';
export {
  StudentPeopleError,
  normalizeStudentCode,
  normalizeStudentProfile,
  normalizeGuardianProfile,
  normalizeGuardianRelationship,
  findStudentByCode,
  createStudentProfile,
  readStudentProfile,
  listStudentProfilesByIds,
  updateStudentProfile,
  setStudentStatus,
  findGuardianByCode,
  createGuardianProfile,
  readGuardianProfile,
  listGuardianProfilesByIds,
  updateGuardianProfile,
  setGuardianStatus,
  createOrUpdateGuardianRelationship,
  updateGuardianRelationship,
  listStudentGuardians,
  findStudentGuardianRelationship,
  lockStudentForScope,
  lockGuardianForScope,
  lockActiveStudentGuardiansForScope,
  listGuardianStudents,
  linkStudentMembership,
  unlinkStudentMembership,
  linkGuardianMembership,
  unlinkGuardianMembership,
  listEligibleStudentAccounts,
  listEligibleGuardianAccounts,
} from './students.js';
export type {
  StudentScope,
  StudentPeopleAudit,
  StudentProfileInput,
  GuardianProfileInput,
  GuardianRelationshipInput,
  GuardianRelationshipType,
} from './students.js';
export { withTenantContext } from './tenant-context.js';
export {
  TimetableError,
  normalizeTimetableSlotInput,
  readWeeklyTimetable,
  lockOrCreateWeeklyTimetable,
  lockWeeklyTimetableForSlot,
  insertTimetableSlot,
  updateTimetableSlot,
  deleteTimetableSlot,
  publishWeeklyTimetable,
} from './timetable.js';
export type { TimetableScope, TimetableActor, TimetableSlotInput, TimetableFilters } from './timetable.js';
export { AcademicSetupError, validateAcademicCode, validateAcademicSession, resolveEnrollmentPlacement, resolveEnrollmentPlacementByCodes, listAcademicSchools, listActiveAcademicMembers, readAcademicSetup, createAcademicSession, createAcademicClass, createAcademicSection, createAcademicSubject, createAcademicAssignment, activateAcademicSession } from './academics.js';
export type { EnrollmentPlacementInput } from './academics.js';
export {
  EnrollmentError,
  normalizeSchoolEnrollmentInput,
  normalizeAcademicEnrollmentInput,
  requireActiveEnrollment,
  createSchoolEnrollment,
  createAcademicEnrollment,
  transferAcademicEnrollment,
  withdrawAcademicEnrollment,
  completeAcademicEnrollment,
  listStudentSchoolEnrollments,
  findActiveSchoolEnrollment,
  findActiveAcademicEnrollment,
  listAcademicEnrollmentHistory,
  listAttendanceRoster,
  lockFinanceEnrollment,
  listFinanceEnrollments,
  hasFinancePlacement,
  listActiveStudentSchoolIds,
  listActiveGuardianSchoolIds,
  listSchoolStudentIds,
  listSchoolGuardianIds,
} from './enrollment.js';
export { beginStudentImportBatch, completeStudentImportBatch, StudentImportBatchError } from './student-import.js';
export type { StudentImportScope, StudentImportCounts } from './student-import.js';
export type {
  EnrollmentScope,
  EnrollmentAudit,
  SchoolEnrollmentInput,
  AcademicEnrollmentInput,
  EnrollmentCloseInput,
  EnrollmentPlacement,
} from './enrollment.js';
export { withAccountContext } from './account-context.js';
export { seedTenantAuthorization } from './authorization-seeding.js';
export { PERMISSION_CATALOG, BUILT_IN_ROLE_TEMPLATES } from './authorization-catalog.js';
export type { PermissionKey, AuthorizationScopeKind } from './authorization-catalog.js';
export {
  createAccountWithMembership,
  createPasswordResetToken,
  isPasswordResetTokenValid,
  consumePasswordResetToken,
  consumeAuthRateLimit,
  checkAuthRateLimit,
  recordSecurityEvent,
  createSession,
  createSessionIfPasswordHashUnchanged,
  findAccountCredentialByEmail,
  getSessionByTokenHash,
  listActiveMemberships,
  normalizeEmailAddress,
  revokeSession,
  revokeSessionsForAccount,
  selectSessionMembership,
  touchSession,
} from './identity-repository.js';
export {
  createMembershipInvitation,
  revokeMembershipInvitation,
  acceptInvitationForExistingAccount,
  acceptInvitationForNewAccount,
  InvitationError,
} from './invite-membership.js';
export {
  canAccessScope,
  listMembershipAuthorizationGrants,
  createCustomRole,
  assignRole,
  revokeRoleAssignment,
  isAuthorizationScopeInTenant,
  listTenantAuthorizationAssignments,
  AuthorizationRepositoryError,
} from './authorization-repository.js';
export type { AuthorizationScope, AuthorizationGrant } from './authorization-repository.js';
export { listTenantAuthorizationRoles, bootstrapTenantAdmin } from './authorization-repository.js';

export {
  AttendanceError,
  calculateAttendanceCompletion,
  changedAttendanceEntries,
  normalizeAttendanceRegisterInput,
  readDailyAttendance,
  getDailyAttendanceRegister,
  saveDailyAttendance,
  listDailyAttendanceEvents,
} from './attendance.js';
export type {
  AttendanceActor,
  AttendanceCompletion,
  AttendanceEntryInput,
  AttendanceRegisterInput,
  AttendanceRosterStudent,
  AttendanceScope,
  AttendanceStatus,
} from './attendance.js';
export {
  FinanceError, minorUnits, balanceFromEntries, getFinanceSchool, listFinanceSchools, listFeeSetup,
  createFeeHead, createFeePlan, createFeePlanLine, getFeePlan, assignFeePlan,
  readFeeStatement, grantFeeConcession, findPaymentByKey, readFeeReceipt,
  recordFeePayment, reverseFeePayment, listFeeOutstanding,
} from './finance.js';
export type { FinanceScope, FinanceActor, PaymentAllocation } from './finance.js';
export {
  AdmissionError,
  nextAdmissionStatus,
  normalizeAdmissionCaseInput,
  createAdmissionCase,
  getAdmissionCase,
  listAdmissionCases,
  updateAdmissionCase,
  transitionAdmissionCase,
  recordAdmissionConversion,
  listAdmissionCaseEvents,
} from './admissions.js';
export type {
  AdmissionActor,
  AdmissionCaseInput,
  AdmissionConversionReferences,
  AdmissionGuardianInput,
  AdmissionListFilters,
  AdmissionRelationship,
  AdmissionScope,
  AdmissionStatus,
  AdmissionTransitionAction,
} from './admissions.js';
